include ../Makefile.inc

# Define all notebook source files.
NOTEBOOK_SOURCE_FILES = conv_nets.py

# Define other source files.
OTHER_SOURCE_FILES = utils.py

# Define resource directories. Currently not used.
# RESOURCE_DIRECTORIES = data model
