include ../Makefile.inc

# Define all notebook source files.
NOTEBOOK_SOURCE_FILES = conv_nets.py

# Define other source files. Currently not used.
OTHER_SOURCE_FILES = utils.py

# Define resource directories.
# RESOURCE_DIRECTORIES = data model
