include ../Makefile.inc

# Define all notebook source files. Not used!
# NOTEBOOK_SOURCE_FILES = somefile.py

# Define other source files.
OTHER_SOURCE_FILES = jupyter/ddpg_learning.ipynb jupyter/deepq_learning.ipynb jupyter/q_learning.ipynb jupyter/env_wrapper.py jupyter/ice_env.py jupyter/nets.py jupyter/utils.py jupyter/rb.py

# Define resource directories.
RESOURCE_DIRECTORIES = jupyter/resources deep_rl rl 
