include ../Makefile.inc

# Define all notebook source files.
NOTEBOOK_SOURCE_FILES = conv_nets.py

# Define other source files.
OTHER_SOURCE_FILES = data_utils.py model.py model_utils.py runner.py trainer.py vis_utils.py

# Define resource directories. Currently not used.
# RESOURCE_DIRECTORIES = data model
