include ../Makefile.inc

# Define all notebook source files.
NOTEBOOK_SOURCE_FILES = LogisticRegression.py

# Define other source files. Currently not used.
# OTHER_SOURCE_FILES = some_file.py

# Define resource directories.
RESOURCE_DIRECTORIES = Data
